### ISSUE TITLE
Prefix not respected when binding to POCO

### ISSUE THREAD

**Issue by rofr** [rofr/Fig#29]
Actual code:
```c#
var settingsBuilder = new SettingsBuilder().UseAppSettingsXml();
var settings = settingsBuilder.Build();
var serviceSettings = settings.Bind<ServiceSettings>(requireAll: true, prefix: "");
```
Exception:
```
System.Collections.Generic.KeyNotFoundException: ServiceSettings.SipEnabled
   at Fig.Settings.Get(Type propertyType, String propertyName, String key, Func`1 default)
   at Fig.Settings.Bind[T](T target, Boolean requireAll, String prefix)
   at Fig.Settings.Bind[T](Boolean requireAll, String prefix)
```

Notice the class name is included in the missing key: `ServiceSettings.SipEnabled`
This should not be the case when passing an empty string as prefix.

**Comment by rofr** [comment]
Applies to Fig 1.5.17 nuget release
